"""Derive an RO-Crate's inputs and outputs (the old CLI's `augment add-io`).

The rules are inherited verbatim from
`fairscape_cli.entailments.find_outputs.calculate_inputs_outputs`, because
downstream consumers — the evidence graph's root traversal in particular —
depend on exactly which datasets land in `EVI:outputs`:

* **outputs** — every dataset not consumed by a computation.
* **inputs** — every sample; every dataset a computation used that was not
  itself generated by one (including ids referenced but absent from the
  graph); and every dataset that is neither used nor generated.

A dataset can be both: unused and ungenerated means it is a standalone input
that is also a leaf output.

Type matching follows the original too, which is looser for datasets
(substring) than for samples and computations (exact). That asymmetry is
load-bearing: a root typed `[..., "ROCrate"]` must not be collected as a
dataset, or the crate lists itself among its own outputs.

Two additions on top of the original, both of which only ever fire where the
original found nothing, so an EVI crate derives exactly what it always did:

* **PROV-only crates.** A crate carrying no EVI vocabulary at all spells its
  entities `prov:Entity`, its activities `prov:Activity`, and its edges
  `prov:wasGeneratedBy` / `prov:used`. Read through `crate`'s vocabulary
  helpers, those resolve to Dataset / Computation / generation / usage — but
  only when no EVI reading applies.
* **The root is never its own output.** The original relied on the root being
  typed `[..., "ROCrate"]` to keep it out of the dataset scan. A PROV-only
  crate's root is a plain `Dataset`, so the root named by the metadata
  descriptor's `about` is skipped explicitly.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional, Sequence, Tuple

from fairscape_artifacts.crate import (
    METADATA_FILENAME,
    evi_type,
    generated_by_ids,
    ref_ids,
    used_dataset_ids,
)

Ref = Dict[str, str]

EVI_INPUTS = "https://w3id.org/EVI#inputs"
EVI_OUTPUTS = "https://w3id.org/EVI#outputs"

_SAMPLE_TYPES = ("https://w3id.org/EVI#Sample", "EVI:Sample")
_COMPUTATION_TYPES = ("https://w3id.org/EVI#Computation", "EVI:Computation")


def _last_type(entity: Dict[str, Any]) -> str:
    """The single `@type` string the original rules are applied to."""
    entity_type = entity.get("@type")
    if isinstance(entity_type, list):
        entity_type = entity_type[-1] if entity_type else ""
    return entity_type or ""


def _root_id(graph: Sequence[Dict[str, Any]]) -> Optional[str]:
    """The id the metadata descriptor points at, if the crate has one."""
    for entity in graph:
        if entity.get("@id") == METADATA_FILENAME:
            about = ref_ids(entity, "about")
            return about[0] if about else None
    return None


def _dedupe(refs: Sequence[Ref]) -> List[Ref]:
    seen, out = set(), []
    for ref in refs:
        if ref["@id"] not in seen:
            seen.add(ref["@id"])
            out.append(ref)
    return out


def calculate(graph: Sequence[Dict[str, Any]]) -> Tuple[List[Ref], List[Ref]]:
    """Return `(inputs, outputs)` for a crate's `@graph`."""
    # dataset id -> was it generated by a computation
    datasets: Dict[str, bool] = {}
    order: List[str] = []
    samples: List[str] = []
    used: set = set()

    root_id = _root_id(graph)

    for entity in graph:
        etype = _last_type(entity)
        entity_id = entity.get("@id")
        # `evi_type` reads EVI typing first and only falls back to PROV when
        # a node carries none, so this widens the original rules without ever
        # overriding them.
        kind = evi_type(entity)

        if entity_id and entity_id != root_id and (
                "Dataset" in etype or kind == "Dataset"):
            if entity_id not in datasets:
                order.append(entity_id)
            datasets[entity_id] = bool(generated_by_ids(entity))

        if etype in _SAMPLE_TYPES and entity_id:
            samples.append(entity_id)

        if etype in _COMPUTATION_TYPES or kind == "Computation":
            for consumed_id in used_dataset_ids(entity):
                used.add(consumed_id)

    inputs: List[Ref] = [{"@id": sid} for sid in samples]

    # Sorted, not set order: `write` persists this list into the crate file,
    # and set iteration order varies per process, so an unsorted list churns
    # the file on every re-run. Membership, not order, is what callers read.
    for used_id in sorted(used):
        # A used dataset is an input unless a computation produced it. An id
        # that is used but absent from the graph is an input by definition —
        # nothing in this crate could have generated it.
        if datasets.get(used_id, False) is False:
            inputs.append({"@id": used_id})

    outputs: List[Ref] = []
    for dataset_id in order:
        if dataset_id not in used:
            outputs.append({"@id": dataset_id})
            if not datasets[dataset_id]:
                inputs.append({"@id": dataset_id})

    return _dedupe(inputs), _dedupe(outputs)


def stored(root: Dict[str, Any]) -> Tuple[List[Ref], List[Ref]]:
    """Inputs/outputs already recorded on a root node, under any spelling."""

    def read(*fields: str) -> List[Ref]:
        for field in fields:
            value = root.get(field)
            if value:
                items = value if isinstance(value, list) else [value]
                return [i for i in items if isinstance(i, dict) and i.get("@id")]
        return []

    return (
        read(EVI_INPUTS, "EVI:inputs", "inputs"),
        read(EVI_OUTPUTS, "EVI:outputs", "outputs"),
    )


def ensure(crate) -> Tuple[List[Ref], List[Ref]]:
    """Inputs/outputs for a crate, deriving them in memory if unrecorded.

    The evidence graph starts its traversal from the root's outputs, so a
    crate that never had `add-io` run against it would otherwise render as a
    single lonely node. This fills them in for the build without touching the
    file on disk — `write` is the only thing that persists.
    """
    inputs, outputs = stored(crate.root)
    if outputs:
        return inputs, outputs
    return calculate(crate.graph)


def write(path: str) -> Tuple[bool, str]:
    """Persist `EVI:inputs` / `EVI:outputs` onto the crate's root entity.

    Rewrites only those two fields; everything else in the file is preserved
    as parsed, unlike the old CLI which also pruned every null in the
    document on its way out.
    """
    from fairscape_artifacts.crate import Crate

    if os.path.isdir(path):
        path = os.path.join(path, "ro-crate-metadata.json")
    if not os.path.exists(path):
        return False, f"RO-Crate metadata file not found at {path}"

    crate = Crate.load(path)
    if not crate.graph:
        return False, "RO-Crate metadata has no @graph"
    if not crate.root:
        return False, "Could not find root entity in RO-Crate"

    inputs, outputs = calculate(crate.graph)
    crate.root[EVI_INPUTS] = inputs
    crate.root[EVI_OUTPUTS] = outputs

    with open(path, "w", encoding="utf-8") as handle:
        json.dump(crate.data, handle, indent=2)

    return True, f"Added {len(inputs)} inputs and {len(outputs)} outputs to {path}"
